---
#common remediation tasks after oscap remediation

- name: enable FIPS in Grub2

# To ensure FIPS mode is enabled, rebuild initramfs by running the following command:
#
# dracut -f
# After the dracut command has been run, add the argument fips=1 to the default GRUB 2 command line for the Linux operating system in /etc/default/grub, in the manner below:
# GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=VolGroup/LogVol06 rd.lvm.lv=VolGroup/lv_swap rhgb quiet rd.shell=0 fips=1"
# Finally, rebuild the grub.cfg file by using the
# grub2-mkconfig -o
# command as follows:
# On BIOS-based machines, issue the following command as root:
# ~]# grub2-mkconfig -o /boot/grub2/grub.cfg
# On UEFI-based machines, issue the following command as root:
# ~]# grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg


- name: set bootloader password

# The grub2 boot loader should have a superuser account and password protection enabled to protect boot-time settings.
#
# To do so, select a superuser account and password and add them into the /etc/grub.d/01_users configuration file.
#
# Since plaintext passwords are a security risk, generate a hash for the pasword by running the following command:
#
# $ grub2-mkpasswd-pbkdf2
# When prompted, enter the password that was selected and insert the returned password hash into the /etc/grub.d/01_users configuration file immediately after the superuser account. (Use the output from grub2-mkpasswd-pbkdf2 as the value of password-hash):
# password_pbkdf2 superusers-account password-hash
# NOTE: It is recommended not to use common administrator account names like root, admin, or administrator for the grub2 superuser account.
#
# To meet FISMA Moderate, the bootloader superuser account and password MUST differ from the root account and password. Once the superuser account and password have been added, update the grub.cfg file by running:
# grub2-mkconfig -o /boot/grub2/grub.cfg
# NOTE: Do NOT manually add the superuser account and password to the grub.cfg file as the grub2-mkconfig command overwrites this file.
# Password protection on the boot loader configuration ensures users with physical access cannot trivially alter important bootloader settings. These include which kernel to use, and whether to enter single-user mode. For more information on how to configure the grub2 superuser account and password, please refer to
#
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Protecting_GRUB_2_with_a_Password.html
